### ISSUE TITLE
텍스트 검색 기능

### ISSUE THREAD

**Issue by osm1892** [ChanggeunBrigade/REECO#3]
알고리즘 과제 연동을 위한 텍스트 검색 기능이 필요합니다.

**Comment by osm1892** [comment]
거의 다 했음

**Comment by paidagogogos** [comment]
커밋한거 업데이트했고 테스트 결과 검색 창에 텍스트 입력 시 fatal exception 오류 발생, findfailarray에서 nullexception도 같이 발생하는 것으로 보임.

**Comment by paidagogogos** [comment]
그리고 검색버튼 집어넣는건 레이아웃이 섹시해보이지 않아서 문자열 검색이 실시간으로 이루어졌으면 좋겠음. 그게 안된다면 다시 이미지버튼을 롤백하겠지만...
